language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -f udagram-feed/Dockerfile -t udagram-feed .
  - docker tag udagram-feed pranjal121997/udagram-feed:latest
  - docker build -f udagram-user/Dockerfile -t udagram-user .
  - docker tag udagram-user pranjal121997/udagram-user:latest
  - docker build -f udagram-frontend/Dockerfile -t udagram-frontend .
  - docker tag udagram-frontend pranjal121997/udagram-frontend:latest
  - docker build -f docker/Dockerfile -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy pranjal121997/udagram-reverseproxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pranjal121997/udagram-feed
  - docker push pranjal121997/udagram-user
  - docker push pranjal121997/udagram-frontend
  - docker push pranjal121997/udagram-reverseproxy